### ISSUE TITLE
could you provide some data for test?

### ISSUE THREAD

**Issue by ForrestPi** [lerouxl/Mesh-deformation-display#1]
Hi, could you provide  some data  in mesh_original  mesh_deformed mesh_deformation   for test?

**Comment by lerouxl** [comment]
Hi ForrestPi,

Yes, I added the Standford bunny mesh in mesh_original and the same one with a random deformation in mesh_deformation. Now you can just launch `main.py` and the mesh difference will be calculated.

I also updated the readme for better clarity and example.

**Comment by ForrestPi** [comment]
thanks
